<a href="https://colab.research.google.com/github/np03cs4a240306-blip/Saurav-Sapkota/blob/main/worksheet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import io

# Define the data as a string
csv_data = """Name,Age,Major
saurav,20,Computer Science
Bob,21,Engineering
Charlie,19,Physics
"""

# Use the io module to simulate a file and read it immediately
df_initial = pd.read_csv(io.StringIO(csv_data))

# Save the DataFrame to disk as 'student.csv'
df_initial.to_csv('student.csv', index=False)

print("student.csv has been successfully created in the current directory.")

student.csv has been successfully created in the current directory.


In [ ]:
import numpy as np
import pandas as pd

# This will now successfully find and read the file
data = pd.read_csv('student.csv')

print(data.head())

      Name  Age             Major
0   saurav   20  Computer Science
1      Bob   21       Engineering
2  Charlie   19           Physics


In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("student.csv")

print(data.head())
print(data.tail())
data.info()
print(data.describe())

X_df = data[['math score', 'reading score']]
Y_df = data['writing score']

X = X_df.to_numpy().T
Y = Y_df.to_numpy()

d = X.shape[0]
W = np.zeros(d)

print(X.shape)
print(W.shape)
print(Y.shape)

train_ratio = 0.8
n = X.shape[1]
n_train = int(train_ratio * n)

indices = np.random.permutation(n)

X_train = X[:, indices[:n_train]]
X_test = X[:, indices[n_train:]]

Y_train = Y[indices[:n_train]]
Y_test = Y[indices[n_train:]]

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

Y_pred = np.dot(W.T, X_train)
print(Y_pred.shape)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

# --- 1. Data Preparation (If you don't have a dataset yet) ---
# We create a dummy DataFrame to ensure the code runs
data = {
    'Hours_Studied': np.random.randint(1, 10, 20),
    'Assignments_Completed': np.random.randint(5, 20, 20),
    'Attendance_Rate': np.random.uniform(0.6, 1.0, 20).round(2),
    'Final_Score': (np.random.rand(20) * 50 + 50).round(0) # This is our target 'y'
}
df = pd.DataFrame(data)

print("--- Original Data Head ---")
print(df.head())
print(f"\nTotal rows in dataset: {len(df)}")


# --- 2. Separate Features (X) and Target (y) ---

# We assume 'Final_Score' is the variable you want to predict (the target)
# X (Features) includes all columns EXCEPT 'Final_Score'
X = df.drop('Final_Score', axis=1)

# y (Target) is the 'Final_Score' column
y = df['Final_Score']

print("\n--- X (Features) Head ---")
print(X.head())

print("\n--- y (Target) Head ---")
print(y.head())


# --- 3. Splitting the Dataset (80-20 Split) ---

# Split the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20, # 20% for testing
    random_state=42 # Ensures the split is the same every time
)

# --- 4. Verify the Split ---

print("\n--- Split Verification (80-20) ---")
print(f"X_train shape (80%): {X_train.shape}")
print(f"X_test shape (20%): {X_test.shape}")
print(f"y_train shape (80%): {y_train.shape}")
print(f"y_test shape (20%): {y_test.shape}")

--- Original Data Head ---
   Hours_Studied  Assignments_Completed  Attendance_Rate  Final_Score
0              5                     17             0.84         78.0
1              4                     14             0.96         66.0
2              3                     17             0.88         84.0
3              7                     18             0.98         89.0
4              5                      5             0.88         97.0

Total rows in dataset: 20

--- X (Features) Head ---
   Hours_Studied  Assignments_Completed  Attendance_Rate
0              5                     17             0.84
1              4                     14             0.96
2              3                     17             0.88
3              7                     18             0.98
4              5                      5             0.88

--- y (Target) Head ---
0    78.0
1    66.0
2    84.0
3    89.0
4    97.0
Name: Final_Score, dtype: float64

--- Split Verification (80-20) ---
X_train shap

In [ ]:
import numpy as np

def cost_function(X, Y, W):
    m = len(Y)
    H = X @ W
    Error = H - Y
    Sum_Squared_Error = Error.T @ Error
    cost = Sum_Squared_Error[0, 0] / (2 * m)
    return cost

In [ ]:
import numpy as np

def cost_function(X, Y, W):
    m = len(Y)
    H = X @ W
    Error = H - Y
    Sum_Squared_Error = Error.T @ Error
    cost = Sum_Squared_Error[0, 0] / (2 * m)
    return cost

# Test Case Inputs
# X @ W results in [3, 7, 11] for W = [1, 1]
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([[3], [7], [11]])
W_test = np.array([[1], [1]])

# Run the Test
computed_cost = cost_function(X_test, Y_test, W_test)

# Verification
expected_cost = 0.0

print(f"X:\n{X_test}")
print(f"Y:\n{Y_test}")
print(f"W:\n{W_test}")
print("-" * 30)
print(f"Manual Expected Cost: {expected_cost}")
print(f"Computed Cost from function: {computed_cost}")

if np.isclose(computed_cost, expected_cost):
    print("\nVerification SUCCESS: The computed cost matches the expected cost of 0!")
else:
    print("\nVerification FAILED: The computed cost does not match the expected cost.")

X:
[[1 2]
 [3 4]
 [5 6]]
Y:
[[ 3]
 [ 7]
 [11]]
W:
[[1]
 [1]]
------------------------------
Manual Expected Cost: 0.0
Computed Cost from function: 0.0

Verification SUCCESS: The computed cost matches the expected cost of 0!


In [ ]:
import numpy as np

def gradient_descent_step(X, Y, W, alpha):

    if W.ndim == 1:
        W = W.reshape(-1, 1)
    if Y.ndim == 1:
        Y = Y.reshape(-1, 1)

    m = len(Y)
    H = X @ W
    Error = H - Y
    Gradient = (1/m) * (X.T @ Error)
    W_new = W - (alpha * Gradient)

    return W_new

X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11]).reshape(-1, 1) # Reshape to (3, 1)
W_initial = np.array([0.5, 0.5]).reshape(-1, 1)  # Initial guess for W, shape (2, 1)
alpha_rate = 0.01

W_new = gradient_descent_step(X_test, Y_test, W_initial, alpha_rate)

print("--- Gradient Descent Step Verification ---")
print(f"Initial W:\n{W_initial.T}")
print(f"Learning Rate (alpha): {alpha_rate}")
print(f"Updated W:\n{W_new.T}")

--- Gradient Descent Step Verification ---
Initial W:
[[0.5 0.5]]
Learning Rate (alpha): 0.01
Updated W:
[[0.63166667 0.66666667]]


In [ ]:
import numpy as np
def gradient_descent(X, Y, W, alpha, iterations):
    if W.ndim == 1:
        W = W.reshape(-1, 1)
    if Y.ndim == 1:
        Y = Y.reshape(-1, 1)

    cost_history = [0] * iterations
    m = len(Y)
    W_update = W

    for iteration in range(iterations):
        Y_pred = X @ W_update
        loss = Y_pred - Y
        dw = (1/m) * (X.T @ loss)
        W_update = W_update - (alpha * dw)
        cost = cost_function(X, Y, W_update)
        cost_history[iteration] = cost

    return W_update, cost_history

In [ ]:

def cost_function(X, Y, W):
    if W.ndim == 1:
        W = W.reshape(-1, 1)
    if Y.ndim == 1:
        Y = Y.reshape(-1, 1)
    m = len(Y)
    H = X @ W
    Error = H - Y
    Sum_Squared_Error = Error.T @ Error
    cost = Sum_Squared_Error[0, 0] / (2 * m)
    return cost
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_initial = np.array([0.0, 0.0])
alpha_rate = 0.01
num_iterations = 100
W_final, cost_history_output = gradient_descent(
    X_test, Y_test, W_initial, alpha_rate, num_iterations
)

print("\n--- Gradient Descent Results ---")
print(f"Final Optimized Weights (W): \n{W_final.T}")
print(f"Initial Cost: {cost_history_output[0]:.4f}")
print(f"Final Cost: {cost_history_output[-1]:.4f}")


--- Gradient Descent Results ---
Final Optimized Weights (W): 
[[0.88123618 1.09375727]]
Initial Cost: 14.5167
Final Cost: 0.0010


In [ ]:
import numpy as np

# --- Cost Function (from To-Do-4) ---
def cost_function(X, Y, W):
    if W.ndim == 1:
        W = W.reshape(-1, 1)
    if Y.ndim == 1:
        Y = Y.reshape(-1, 1)
    m = len(Y)
    H = X @ W
    Error = H - Y
    Sum_Squared_Error = Error.T @ Error
    cost = Sum_Squared_Error[0, 0] / (2 * m)
    return cost

# --- Gradient Descent Function (from To-Do-6) ---
def gradient_descent(X, Y, W, alpha, iterations):
    # Ensure W and Y are column vectors for robust matrix operations
    if W.ndim == 1:
        W = W.reshape(-1, 1)
    if Y.ndim == 1:
        Y = Y.reshape(-1, 1)

    cost_history = [0] * iterations
    m = len(Y)
    W_update = W

    for iteration in range(iterations):
        # Step 1: Hypothesis Values (Prediction: H = X @ W)
        Y_pred = X @ W_update

        # Step 2: Difference between Hypothesis and Actual Y (Error)
        loss = Y_pred - Y

        # Step 3: Gradient Calculation (Gradient = (1/m) * X.T @ loss)
        dw = (1/m) * (X.T @ loss)

        # Step 4: Updating Values of W using Gradient
        W_update = W_update - (alpha * dw)

        # Step 5: New Cost Value
        cost = cost_function(X, Y, W_update)
        cost_history[iteration] = cost

    return W_update, cost_history

# --- Test Execution ---

# Generate random test data
np.random.seed(0) # For reproducibility
X = np.random.rand(100, 3) # 100 samples, 3 features
Y = np.random.rand(100)
W = np.random.rand(3) # Initial guess for parameters
# Set hyperparameters
alpha = 0.01
iterations = 1000

# Test the gradient_descent function
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)

# Print the results
print("--- Gradient Descent Test Results ---")
print(f"Initial W (Guess): {W}")
print(f"Learning Rate (alpha): {alpha}")
print(f"Iterations: {iterations}")
print("-" * 35)
print(f"Final Parameters (Optimized W):\n{final_params.T}")
print(f"Initial Cost: {cost_history[0]:.6f}")
print(f"Final Cost: {cost_history[-1]:.6f}")

--- Gradient Descent Test Results ---
Initial W (Guess): [0.4012595  0.92929142 0.09961493]
Learning Rate (alpha): 0.01
Iterations: 1000
-----------------------------------
Final Parameters (Optimized W):
[[0.20551667 0.54295081 0.10388027]]
Initial Cost: 0.107112
Final Cost: 0.054355


In [ ]:
import numpy as np

def rmse(Y, Y_pred):
    if Y.shape != Y_pred.shape:
        if Y.ndim > Y_pred.ndim:
             Y_pred = Y_pred.reshape(-1, 1)
        elif Y_pred.ndim > Y.ndim:
             Y = Y.reshape(-1, 1)

    m = len(Y)

    squared_error = (Y_pred - Y)**2

    mse = np.sum(squared_error) / m

    rmse = np.sqrt(mse)

    return rmse

# Test data (actual values)
Y_actual = np.array([10, 20, 30])

# Predicted values
Y_predicted = np.array([10.5, 19.8, 31.0])

calculated_rmse = rmse(Y_actual, Y_predicted)

print("--- RMSE Calculation Test ---")
print(f"Actual Y:   {Y_actual}")
print(f"Predicted Y: {Y_predicted}")
print(f"Calculated RMSE: {calculated_rmse:.4f}")

--- RMSE Calculation Test ---
Actual Y:   [10 20 30]
Predicted Y: [10.5 19.8 31. ]
Calculated RMSE: 0.6557


In [ ]:
import numpy as np

# Model Evaluation - R2
def r2(Y, Y_pred):

    if Y.shape != Y_pred.shape:
        if Y.ndim > Y_pred.ndim:
             Y_pred = Y_pred.reshape(-1, 1)
        elif Y_pred.ndim > Y.ndim:
             Y = Y.reshape(-1, 1)

    mean_y = np.mean(Y)

    ss_tot = np.sum((Y - mean_y)**2)
    ss_res = np.sum((Y - Y_pred)**2)

    # R-Squared Formula
    r2 = 1 - (ss_res / ss_tot)

    return r2
Y_actual = np.array([10, 20, 30, 40])
Y_predicted_good = np.array([11, 21, 29, 39])
Y_predicted_poor = np.array([25, 25, 25, 25])

r2_good = r2(Y_actual, Y_predicted_good)
r2_poor = r2(Y_actual, Y_predicted_poor)

print("--- R-Squared Calculation Test ---")
print(f"R2 for Good Fit (closer to 1.0): {r2_good:.4f}")
print(f"R2 for Poor Fit (closer to 0.0): {r2_poor:.4f}")

--- R-Squared Calculation Test ---
R2 for Good Fit (closer to 1.0): 0.9920
R2 for Poor Fit (closer to 0.0): 0.0000
